### ISSUE TITLE
Error when using Rust build pack.

### ISSUE THREAD

**Issue by kaaquist** [jenkins-x-buildpacks/jenkins-x-classic#25]
Trying to do a `jx project import` of a rust application.  
The import goes well but I get an error when the pipeline tries to build, or copy the build.
```text
Showing logs for build <github user>/<application name>/master #8 release stage from-build-pack and container step-build-copy-bin
cp: cannot stat '/tekton/home/.cargo/bin/REPLACE_ME_APP_NAME': No such file or directory
Pipeline failed on stage 'from-build-pack' : container 'step-build-copy-bin'. The execution of the pipeline has stopped. 
```
Error: `cp: cannot stat '/tekton/home/.cargo/bin/REPLACE_ME_APP_NAME': No such file or directory`  
It seems there is missing some replacement of the `REPLACE_ME_APP_NAME` placeholder.

Line: https://github.com/jenkins-x-buildpacks/jenkins-x-classic/blob/1271ce2a3a9bfb741426661c72646b591d13f9b5/packs/rust/pipeline.yaml#L31

Not sure if I should override the line/part of the pipeline, or if this is just a "feature" that needs fixing?

I have created an override block and that did the trick.
From jenkins-x.yaml
```yaml
buildPack: rust
pipelineConfig:
  pipelines:
    overrides:
      - name: copy-bin
        step: 
          sh: echo "hello you!"
          name: new-bogus-bin
```
But I guess a fix to the real problem would be great. 

I can see that this here bug relates to Issue #18, where there are a fix in PR #20
